### ISSUE TITLE
Beh numpy problem

### ISSUE THREAD

**Issue by kuberap** [MQ37/creathon#3]
Hlásí mi to tuto chybu (mám numpy v 2.1.1):
python3.12 info.py -fh /localdata/Scratch/medical/data/2024-05-10/dataset_0/TBI_011_v2_2_1_22.hdf5 -fa /localdata/Scratch/medical/data/2024-05-10/dataset_0/TBI_011_v2_2_1_22.artf
Traceback (most recent call last):
  File "/home/pkubera/creathon-data-test/creathon/info.py", line 76, in <module>
    main(args)
  File "/home/pkubera/creathon-data-test/creathon/info.py", line 15, in main
    icp_signal, abp_signal = read_hdf5(hdf5_filepath)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkubera/creathon-data-test/creathon/lib/funcs.py", line 67, in read_hdf5
    icp_signal = read_hdf5_signal(hdf5_file, signal="icp")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkubera/creathon-data-test/creathon/lib/funcs.py", line 51, in read_hdf5_signal
    stream = wave_data.get_data_stream(start_time, stream_duration_microsec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pkubera/creathon-data-test/creathon/lib/hdf5_reader_module.py", line 511, in get_data_stream
    self._data_reader.load_raw_data_set(page_start_time, page_len_microsec)
  File "/home/pkubera/creathon-data-test/creathon/lib/hdf5_reader_module.py", line 248, in load_raw_data_set
    self._sig_stream[self._sig_stream==INVALID_VALUE] = np.NaN
                                                        ^^^^^^
  File "/home/pkubera/creathon-data-test/creathon/venv/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

**Comment by kuberap** [comment]
funguje.
